name: Progress Bar CI

on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'erisetyawan166'
          git config user.email 'erisetyawan34@gmail.com'
          git commit -am "Mari kita hijaukan :3🌳"
          git push
